@startuml
actor User as user
left to right direction

package AppInvoice {

package Tickets {
(GenerateTicket) as genticket
user --> genticket
}

package Invoice {
(Invoice) as invoice
user --> invoice
}

note right of (Invoice)
- Find ticket active
- Get ticket time, calculate cost
- Close ticket
end note

@enduml
